### ISSUE TITLE
Campus-level: nested table showing preliminary STAAR _growth_ data, 2017-2019

### ISSUE THREAD

**Issue by jmostipak** [cmyricktt/staar_prelim_report_fy2020#3]
this is modeled after the TEA-generated district report shared by Steph via email on 13 June 2019:

<img width="852" alt="Screen Shot 2019-06-13 at 1 03 34 PM" src="https://user-images.githubusercontent.com/30671679/59456319-b1b08280-8ddb-11e9-9e6a-5e99fbe6476a.png">

**Comment by cmyricktt** [comment]
Completed! :-)
